### ISSUE TITLE
Injection fails when an unavailable assembly is present in any other mod

### ISSUE THREAD

**Issue by AdalynBlack** [Saradora/UnityMDK#1]
If an assembly is referenced in any other mod, but that assembly isn't available at runtime UnityMDK crashes while attempting to run the scene injector
This is the full error as seen in game:
```
[Error  : Unity Log] FileNotFoundException: Could not load file or assembly 'UnityEditor.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:
System.MonoCustomAttrs.IsDefined (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType, System.Boolean inherit) (at <787acc3c9a4c471ba7d971300105af24>:IL_0027)
System.RuntimeType.IsDefined (System.Type attributeType, System.Boolean inherit) (at <787acc3c9a4c471ba7d971300105af24>:IL_0038)
UnityMDK.Injection.SceneInjection.RegisterInjector (System.Type type) (at <b44fcc8444a94ced8cd185102cc2a2a6>:IL_0000)
UnityMDK.Injection.SceneInjection.Initialize () (at <b44fcc8444a94ced8cd185102cc2a2a6>:IL_009C)
UnityMDK.Injection.SceneConstructor.Awake () (at <b44fcc8444a94ced8cd185102cc2a2a6>:IL_000B)
UnityEngine.GameObject:AddComponent()
UnityMDK.UnityMDK:CreateSceneConstructor(Scene)
UnityMDK.UnityMDK:Awake()
UnityEngine.GameObject:AddComponent()
UnityMDK.PluginInitializer:OnSceneLoaded(Scene, LoadSceneMode)
UnityEngine.SceneManagement.SceneManager:Internal_SceneLoaded(Scene, LoadSceneMode)
```
This type of issue indicates a problem with the mod that referenced an invalid assembly such as this, but it also seems logical that UnityMDK should be able to detect these issues, create an error in the log to note the problem, and continue execution as normal regardless

**Comment by Saradora** [comment]
Oh my god thank you so much for finding more about this issue it was driving me mad haha, I will investigate at once c:

I'm really not surprised the issue comes from this instead of ScanTweaks, injection failure was really the only logical explanation for the reported behaviour

**Comment by Saradora** [comment]
Indeed simply installing LethalExpansionCore breaks injection!

**Comment by Saradora** [comment]
And sure enough a simple exception catching gets rid of the issue

**Comment by Saradora** [comment]
The issue appears to be fixed, i'll be closing it

Thank you so much for taking the time to help fix this issue this is greatly appreciated c:

**Comment by Saradora** [comment]
Welp, had to fix again because for some reason not having UnityExplorer introduced another exception, but at least it's fixed
